services:
  mudlet: &base-settings
    image: mudlet:dev
    build:
      dockerfile: docker/Dockerfile
      context: ..

  dev:
    <<: *base-settings
    volumes:
      - settings:/home/mudlet/settings
      - ../CMakeLists.txt:/home/mudlet/CMakeLists.txt
      - ../src:/home/mudlet/src
      - ../translations:/home/mudlet/translations
      - ../test:/home/mudlet/test
    command: qtcreator CMakeLists.txt -settingspath /home/mudlet/settings/

volumes:
  settings:
